#!/bin/sh

set -eu

if [ "$1" = "triggered" ]
then
    if [ "$2" = "/opt/omi/bin/omiserver" ]
    then
        logger "omitriggertest.postinst: Triggered for /opt/omi/bin/omiserver"
	touch /tmp/omi_is_updated
    else
        logger "omitriggertest.postinst: Unknown trigger: $2"
    fi
fi
